version: "3.7"

networks:
  symfony:

services:
  nginx:
    image: library/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - "php"
      - "db"
      - "phpmyadmin"
    networks:
      - symfony
    volumes:
    - ./src/app:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: zvendo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql/
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - /sessions
    networks:
      - symfony
    links:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis/data
    networks:
      - symfony