version: "3.7"

networks:
  {{app-name}}:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx
    ports:
      - "8060:80"
    depends_on:
      - "php"
      - "postgres"
    networks:
      - {{app-name}}
    volumes:
    - ./src/app:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: library/postgres:alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: {{db-name}}
    networks:
      - {{app-name}}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "82:80"
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - {{app-name}}

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - {{app-name}}
